name: Publish

on:
  push:
    branches:
        - main

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        sudo apt-get install -y libusb-1.0-0-dev graphviz texlive
        wget https://github.com/vovkos/doxyrest/releases/download/doxyrest-2.1.3/doxyrest-2.1.3-linux-amd64.tar.xz
        tar -xf doxyrest-2.1.3-linux-amd64.tar.xz
        echo "$(pwd)/doxyrest-2.1.3-linux-amd64/bin/" >> $GITHUB_PATH
        mkdir doxygen
        cd doxygen
        git clone https://github.com/doxygen/doxygen.git
        cd doxygen
        git checkout Release_1_9_2
        mkdir build
        cd build
        cmake ..
        cmake --build . -j`nproc`
        sudo make install
        cd ../../..
        ./get_openvino_repo.sh
        cd openvino/docs
        python -m pip install -r requirements.txt
        cd openvino_sphinx_theme/
        python setup.py install --user
        cd ../../..    
    - name: Build the docs
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        ./build_doxygen.sh
        ./get_doxygen_rst.sh
        ./get_zoo_models.sh
        ./get_notebooks.sh
        python -m venv .venv
        source .venv/bin/activate
        ./install_dependencies.sh
        sphinx-build -b html . _build/html
        touch _build/html/.nojekyll
        mkdir -p _build/html/pages/documentation/performance-benchmarks/_assets
        cp -r pages/documentation/performance-benchmarks/_assets/*.csv _build/html/pages/documentation/performance-benchmarks/_assets/
    - name: Push the docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/html
        publish_branch: latestHTML
